### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by afsungur** [atom/tabs#100]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.58.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:490

TypeError: undefined is not a function
  at Object.module.exports.Pane.promptToSaveItem [as defaultSavePrompt] (/Applications/Atom.app/Contents/Resources/app/src/pane.js:490:23)
  at Pane.promptToSaveItem (/Users/fuat/.atom/packages/save-session/lib/save-prompt.coffee:21:15)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:442:18)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -1:21.3 core:close (input.hidden-input)
     -0:48.3 editor:newline (input.hidden-input)
  2x -0:47.1 core:backspace (input.hidden-input)
     -0:45.9 editor:newline (input.hidden-input)
  5x -0:44.8 core:backspace (input.hidden-input)
     -0:34.1 editor:newline (input.hidden-input)
     -0:26.9 core:backspace (input.hidden-input)
     -0:26.6 editor:newline (input.hidden-input)
     -0:22.9 core:save (input.hidden-input)
     -0:19.9 core:copy (input.hidden-input)
     -0:12.8 editor:newline (input.hidden-input)
     -0:12.4 core:paste (input.hidden-input)
     -0:11.0 core:select-all (input.hidden-input)
     -0:10.3 core:copy (input.hidden-input)
     -0:00.3 core:select-all (input.hidden-input)
     -0:00.0 core:copy (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "save-session"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
atom-beautify, v0.17.2
file-icons, v1.4.3
git-log, v0.2.0
git-tab-status, v1.3.0
hide-files, v0.1.2
recent-files, v0.3.0
selection-count, v1.6.3
vim-mode, v0.21.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
@benogle any ideas why this stack trace targeted the tabs package instead of the save-session package?

Looks like `save-session` is higher up on the stack

```
at Pane.promptToSaveItem (/Users/fuat/.atom/packages/save-session/lib/save-prompt.coffee:21:15)
at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:442:18)
at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
```

**Comment by benogle** [comment]
looking...

**Comment by benogle** [comment]
One thing that might be causing this is that the save session plugin is disabled, but it's in the trace. My guess as to whats happening:

1. Atom started with save session enabled
2. Disable save session, but it doesnt really clean itself up
3. Do something that calls into save-session
4. error!

Though the trace parser looks at loaded packages, and save-session should still be loaded.

**Comment by benogle** [comment]
Looks like save session monkey patches `promptToSaveItem`

**Comment by benogle** [comment]
I think this is a fluke. Going to close this out as it comes from save-session monkey patching `Pane::promptToSaveItem`, and then being disabled. When there are multiple packages in the stack, the top one should be used. Notifications package contains tests for this case.
