### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getUri' of undefined

### ISSUE THREAD

**Issue by persistence911** [atom/tabs#103]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.58.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getUri' of undefined

```
At /opt/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:374

TypeError: Cannot read property 'getUri' of undefined
  at TabBarView.module.exports.TabBarView.onDragStart (/opt/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:374:22)
  at tabs-tab.<anonymous> (/opt/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/opt/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -8:03.4 core:backspace (input.hidden-input)
  2x -8:01.6 core:confirm (input.hidden-input)
  2x -4:03.2 core:backspace (input.hidden-input)
     -3:48.3 core:confirm (input.hidden-input)
     -2:38.4 command-palette:toggle (input.hidden-input)
     -2:37.1 core:backspace (input.hidden-input)
     -2:33.5 core:confirm (input.hidden-input)
     -2:33.4 settings-view:install-packages (input.hidden-input)
  3x -0:56.6 window:increase-font-size (input.hidden-input)
  2x -0:54.2 core:move-down (input.hidden-input)
     -0:44.0 command-palette:toggle (input.hidden-input)
     -0:39.2 core:confirm (input.hidden-input)
     -0:39.1 settings-view:install-packages (input.hidden-input)
     -0:33.3 core:confirm (input.hidden-input)
     -0:20.8 core:save (div.settings-view.pane-item)
     -0:00.0 development-server:toggle (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-development-server, v0.3.2
language-aspx, v0.2.0
language-csharp, v0.3.0
language-cshtml, v0.1.0
language-fsharp, v0.8.4
monokai, v0.9.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
I'm guessing this is an issue in atom-development-server. Can you reproduce the issue in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by izuzak** [comment]
Also, can you clarify what you did to trigger the exception? Sharing as many details as possible would be helpful.
