### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/usr/share/atom/resources/app/node_modules/welcome/docs/linux/welcome.md'

### ISSUE THREAD

**Issue by cameron581** [atom/tabs#110]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.64.0

### Stack Trace

Uncaught Error: EACCES, permission denied '/usr/share/atom/resources/app/node_modules/welcome/docs/linux/welcome.md'

```
At /usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:318

Error: EACCES, permission denied '/usr/share/atom/resources/app/node_modules/welcome/docs/linux/welcome.md'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/usr/share/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:234:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:304:21)
  at File.module.exports.File.write (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:617:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:538:16)
  at Pane.module.exports.Pane.promptToSaveItem (/usr/share/atom/resources/app/src/pane.js:511:23)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:456:18)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/encoding-selector/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/encoding-selector/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -1:41.8 core:delete (atom-text-editor.editor)
  2x -1:40.9 core:move-down (atom-text-editor.editor)
  8x -1:40.0 core:move-right (atom-text-editor.editor)
 12x -1:37.4 core:backspace (atom-text-editor.editor)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by benogle** [comment]
Looks like you just edited the welcome.md file, and tried to save it, correct?

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/atom/atom/pull/5424 and should no longer be an issue in the latest Atom version, 0.194
