### ISSUE TITLE
Uncaught TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by antares38** [atom/tabs#112]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: linux 3.2.0-72-generic
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.64.0

### Stack Trace

Uncaught TypeError: Cannot read property 'index' of undefined

```
At /usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95

TypeError: Cannot read property 'index' of undefined
  at IntervalSkipList.module.exports.IntervalSkipList.findIntersecting (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95:31)
  at MarkerManager.module.exports.MarkerManager.findMarkers (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-manager.js:156:46)
  at TextBuffer.module.exports.TextBuffer.findMarkers (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:661:27)
  at DisplayBuffer.module.exports.DisplayBuffer.findMarkers (/usr/share/atom/resources/app/src/display-buffer.js:1296:26)
  at DisplayBuffer.module.exports.DisplayBuffer.decorationsForScreenRowRange (/usr/share/atom/resources/app/src/display-buffer.js:1189:20)
  at TextEditor.module.exports.TextEditor.decorationsForScreenRowRange (/usr/share/atom/resources/app/src/text-editor.js:1255:33)
  at [object Object].module.exports.React.createClass.render (/usr/share/atom/resources/app/src/text-editor-component.js:77:30)
  at [object Object]._renderValidatedComponent (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1249:34)
  at [object Object].updateComponent (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1179:33)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1123:10)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1063:14)
  at runBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:152:17)
  at ReactReconcileTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.replaceState (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:878:20)
  at [object Object].ReactCompositeComponentMixin.setState (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:850:10)
  at [object Object].module.exports.React.createClass.focused (/usr/share/atom/resources/app/src/text-editor-component.js:619:14)
  at [object Object].boundMethod [as focused] (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at atom-text-editor.TextEditorElement.focused (/usr/share/atom/resources/app/src/text-editor-element.js:199:55)
  at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app/src/pane-element.js:125:25)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:328:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app/src/pane.js:322:19)
  at Pane.module.exports.Pane.activatePreviousItem (/usr/share/atom/resources/app/src/pane.js:293:21)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:393:16)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:457:16)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:154:24)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -0:27.9 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v3.5.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by 1j01** [comment]
https://github.com/atom/atom/issues/4891

**Comment by izuzak** [comment]
Closing in favor of https://github.com/atom/atom/issues/4891 (thanks for the pointer, @1j01).
