### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by redaced** [atom/tabs#143]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: linux 4.0.0-040000-generic
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.68.0

### Stack Trace

Uncaught Error: Unable to watch path

```
At /usr/share/atom/resources/app.asar/src/pane.js:759

Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:467:109)
  at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:339:14)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:913:17)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:567:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.promptToSaveItem (/usr/share/atom/resources/app.asar/src/pane.js:495:23)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:441:18)
  at tabs-tab.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:163:24)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -2:58.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:45.3.0 core:copy (atom-text-editor.editor.is-focused)
     -2:40.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:40.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:39.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:39.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:35.7.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  3x -2:35.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:36.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:35 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:33.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:31.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:31.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31 core:save (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
laravel, v0.7.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @redaced -- check out https://github.com/atom/atom/issues/2082. If that doesn't help, then check out some of the other [open issues related to this](https://github.com/atom/atom/search?q=Unable+to+watch+path&type=Issues&utf8=%E2%9C%93).

**Comment by redaced** [comment]
thanks @izuzak
