### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollViewNode' of null

### ISSUE THREAD

**Issue by varemenos** [atom/tabs#181]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.80.0

### Stack Trace

Uncaught TypeError: Cannot read property 'scrollViewNode' of null

```
At /Users/akakoulidis/.atom/init.js:6

TypeError: Cannot read property 'scrollViewNode' of null
  at /Users/akakoulidis/.atom/init.js:6:34
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:338:18
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-container.js:375:27)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.moveItemToPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:415:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:720:20)
  at TabBarView.module.exports.TabBarView.onDrop (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:638:23)
  at space-pen-ul.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "regex-railroad-diagram"
    ],
    "themes": [
      "one-dark-ui",
      "obscurity-syntax"
    ]
  },
  "tabs": {
    "tabScrolling": true,
    "usePreviewTabs": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
autoclose-html, v0.18.0
bezier-curve-editor, v0.7.2
color-picker, v2.0.4
disable-keybindings, v0.5.0
docblockr, v0.7.2
duplicate-line-or-selection, v0.5.0
emmet, v2.3.10
file-type-icons, v0.7.0
flex-tool-bar, v0.4.2
git-projects, v1.14.1
git-tab-status, v1.9.2
hex, v0.6.2
highlight-selected, v0.10.0
language-apache, v1.3.0
language-jade, v0.4.0
linter, v0.12.7
linter-jscs, v1.12.0
linter-jshint, v0.1.6
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
obscurity-syntax, v0.5.4
pdf-view, v0.22.0
save-session, v0.15.5
set-syntax, v0.3.0
svg-preview, v0.6.0
symbols-tree-view, v0.9.3
synced-sidebar, v0.4.0
tab-control, v0.6.3
timecop, v0.31.0
tool-bar, v0.1.7
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@varemenos The information you provided indicates that something in your init script is causing these problems: `At /Users/akakoulidis/.atom/init.js:6`. If you'd like more advice on debugging this or think this isn't a problem in that script -- please include the contents of that file here.

**Comment by varemenos** [comment]
The content of my init.js are posted below, it unbinds the events that are bound in the middle click (there is no other way to currently disable the middle clicking in Linux). I will go ahead and modify my script to check if the things the script is using exist. Thank you for the reply Ivan.

```js
atom.workspace.observeTextEditors(function(editor) {
	var editorComponent;
	var scrollViewNode;

	editorComponent = atom.views.getView(editor).component;
	scrollViewNode = editorComponent.scrollViewNode;
	scrollViewNode.removeEventListener('mousedown', editorComponent.onMouseDown);

	return scrollViewNode.addEventListener('mousedown', function(event) {
		if (event.button === 1) {
			return;
		}

		return editorComponent.onMouseDown(event);
	});
});
```
