### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by ynnoj** [atom/tabs#186]
1. Open any file using the project file shortcut (Cmd+T).
2. Error not always triggered. Occasionally the file will open, but will not become active in pane.

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.81.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

ReferenceError: path is not defined
  at TextEditor.getLongTitle (/Users/J/.atom/init.coffee:19:16)
  at tabs-tab.module.exports.TabView.updateTitle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:232:91)
  at tabs-tab.module.exports.TabView.updateTitle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:243:19)
  at TabBarView.module.exports.TabBarView.insertTabAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:357:11)
  at TabBarView.module.exports.TabBarView.addTabForItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:336:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:160:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:297:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:481:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:36.1.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-spacegray-dark-syntax.theme-spacegray-dark-ui)
     -0:33.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:33.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:02.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "spacegray-dark-ui",
      "spacegray-dark-syntax"
    ],
    "disabledPackages": [
      "emmet"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5
atom-handlebars, v0.5.0
color-picker, v2.0.7
editorconfig, v1.0.0
highlight-line, v0.11.0
jshint, v1.3.7
project-manager, v1.15.10
spacegray-dark-syntax, v0.2.0
spacegray-dark-ui, v0.12.0
sync-settings, v0.4.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Might be a problem in your init.coffee script -- notice the top of the stack trace:

```
at TextEditor.getLongTitle (/Users/J/.atom/init.coffee:19:16)
```

Can you post the contents of your init.coffee file?

**Comment by ynnoj** [comment]
Ah! I had added a few lines to change the way file names are displayed on the tabs. This was working in older versions (perhaps pre `0.200.0`). What changes are required to keep this custom setting?

### js
{TextEditor} = require 'atom'
TextEditor::getLongTitle = ->
  if sessionPath = @getPath()
    fileName = path.basename(sessionPath)
    directory = atom.project.relativize(path.dirname(sessionPath))
    directory = if directory.length > 0 then directory.split('/').pop() else path.basename(path.dirname(sessionPath))
    "#{directory}/#{fileName}"
  else
    'untitled'

**Comment by izuzak** [comment]
Try adding `path = require 'path'` to the top of the script.

**Comment by ynnoj** [comment]
Great, thanks @izuzak.
