### ISSUE TITLE
Uncaught Error: Cannot find module 'shell'Error: Cannot find module 'shell'    at Function.Modu...

### ISSUE THREAD

**Issue by Zyneak** [atom/tabs#192]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.81.0

### Stack Trace

Uncaught Error: Cannot find module 'shell'
Error: Cannot find module 'shell'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at AtomApplication.<anonymous> (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-application.js:312:16)
    at emitNone (events.js:67:13)
    at AtomApplication.emit (events.js:163:7)
    at AtomApplication.module.exports.AtomApplication.sendCommand (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-application.js:497:22)
    at item.click (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\application-menu.js:226:45)
    at MenuItem.click (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\api\lib\menu-item.js:44:20)

```
At C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module 'shell'
Error: Cannot find module 'shell'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at AtomApplication.<anonymous> (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-application.js:312:16)
    at emitNone (events.js:67:13)
    at AtomApplication.emit (events.js:163:7)
    at AtomApplication.module.exports.AtomApplication.sendCommand (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-application.js:497:22)
    at item.click (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\application-menu.js:226:45)
    at MenuItem.click (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\api\lib\menu-item.js:44:20)
  at metaToValue (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at Object.exports.require (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:161:34)
  at Atom.module.exports.Atom.confirm (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\atom.js:724:23)
  at Pane.module.exports.Pane.promptToSaveItem (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:488:21)
  at Pane.module.exports.Pane.destroyItem (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:441:18)
  at HTMLDivElement.<anonymous> (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Jordan\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -3:02.6.0 welcome:show (ul.list-inline.tab-bar.inset-panel)
     -2:27.1.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
 34x -2:14.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @Zyneak, can you please share some steps as to how you got to this error?  Thanks.
