### ISSUE TITLE
Failed to activate the tabs package

### ISSUE THREAD

**Issue by Bultack** [atom/tabs#224]
[Enter steps to reproduce below:]

1. Fork the project atom/tabs
2. Clone it
3. Go to the folder using the cli and run `apm link --dev`
4. run `atom --dev`

**Atom Version**: 1.0.19
**System**: Windows 10
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.85.0

### Stack Trace

Failed to activate the tabs package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (D:\www\tabs\lib\tab-bar-view.coffee:4:13)
  at Object.<anonymous> (D:\www\tabs\lib\tab-bar-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (D:\www\tabs\lib\main.coffee:29:18)
  at Package.module.exports.Package.activateNow (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:245:19)
  at C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:469:29
  at Config.module.exports.Config.transact (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:324:16)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:670:21)
  at Object.<anonymous> (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\Alejandro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///C:/Users/Alejandro/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///C:/Users/Alejandro/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:35:9)

```

### Config

```json
{
  "core": {},
  "tabs": {
    "usePreviewTabs": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.8.4
emmet, v2.3.13
file-icons, v1.6.11
highlight-selected, v0.10.1
linter, v1.8.1
linter-jshint, v1.2.1
minimap, v4.13.4
minimap-find-and-replace, v4.3.1
minimap-highlight-selected, v4.3.1

# Dev
tabs, v0.85.0
```

**Comment by benogle** [comment]
You need to run `apm install` in the tabs directory.

**Comment by LukasHechenberger** [comment]
Has there been any progress on this issue?
I can't even start Atom without getting this error - *I even reinstalled Atom*. Pretty annoying...

```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
Make sure you haven't accidentally linked or manually installed the tabs package.  `apm unlink tabs && apm unlink -d tabs && apm uninstall tabs` should do the trick if you have.

**Comment by LukasHechenberger** [comment]
Thanks, this led me into the right direction. I uninstalled all packages and reinstalled them one by one. It turned out that a single packages was the problem, although the tabs package was not installed there (at least not listed in the package's dependencies)..
