### ISSUE TITLE
Uncaught TypeError: this.item.getTitle is not a function

### ISSUE THREAD

**Issue by james-y** [atom/tabs#239]
### Reproduce
Related code snippet when trying to add a new instance of a TextEditor to an empty Pane.
Probably just trying to do doing this in an incorrect way...
```
@splitPane = atom.workspace.getActivePane().splitRight(copyActiveItem: false)
@splitEditorPane = atom.workspace.getActivePane()
@splitTextEditor = document.createElement('atom-text-editor')
@splitEditorPane.addItem @splitTextEditor
```

**Atom Version**: 1.2.3
**System**: Ubuntu 14.04.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught TypeError: this.item.getTitle is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-view.js:254

TypeError: this.item.getTitle is not a function
    at tabs-tab.module.exports.TabView.updateTitle (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-view.js:254:27)
    at tabs-tab.module.exports.TabView.initialize (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-view.js:34:12)
    at atom-tabs.TabBarView.addTabForItem (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:287:15)
    at /usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:152:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:340:20)
    at new ShadowEditor (/home/jamesy/Development/github/atom-git-client/lib/shadow-editor.coffee:26:23)
    at [object Object].module.exports.AtomGitClient.toggle (/home/jamesy/Development/github/atom-git-client/lib/atom-git-client.coffee:101:25)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-git-client:toggle (/home/jamesy/Development/github/atom-git-client/lib/atom-git-client.coffee:68:97)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
```

### Commands

```
     -0:00.8.0 atom-git-client:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.git, vundefined
atom-git-client, v0.0.0

# Dev
No dev packages
```

**Comment by james-y** [comment]
Nevermind, figured it out.
Could use this function instead:
``` 
@splitTextEditor = atom.workspace.buildTextEditor()
```
Which gets the TextEditor built correctly.
