### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'E:\github\LSTM_in_GL\using_torch\practical5-master\m...

### ISSUE THREAD

**Issue by prm10** [atom/tabs#247]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught Error: Adding a pane item with URI 'E:\github\LSTM_in_GL\using_torch\practical5-master\main.lua' that has already been destroyed

```
At C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:331

Error: Adding a pane item with URI 'E:\github\LSTM_in_GL\using_torch\practical5-master\main.lua' that has already been destroyed
    at Pane.module.exports.Pane.addItem (C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:331:15)
    at Pane.module.exports.Pane.activateItem (C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:315:14)
    at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:310:19)
    at Pane.module.exports.Pane.activatePreviousItem (C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:277:21)
    at Pane.module.exports.Pane.removeItem (C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:391:16)
    at Pane.module.exports.Pane.destroyItem (C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:453:16)
    at atom-tabs.TabBarView.onClick (C:\Users\prm14\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:695:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-lua, v0.9.4
markdown-preview-plus, v2.2.2
minimap, v4.18.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Closing in favor of #258.
