### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Manabu-Shirato** [atom/tabs#253]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.10.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At /Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24

TypeError: Cannot read property 'forEach' of undefined
    at module.exports.CompositeDisposable.dispose (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom 2.app/Contents/Resources/app.asar/src/pane.js:648:20)
    at Pane.module.exports.Model.destroy (/Applications/Atom 2.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom 2.app/Contents/Resources/app.asar/src/pane.js:639:39)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom 2.app/Contents/Resources/app.asar/src/pane.js:411:21)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom 2.app/Contents/Resources/app.asar/src/pane.js:453:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
     -0:18.1.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:16.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Remote-FTP",
      "japanese-wrap"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.28.21
atom-html-preview, v0.1.13
atom-webbrowser, v2.1.4
autoclose-html, v0.20.0
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
browser-refresh-on-save, v0.0.4
compare-files, v0.6.2
foldername-tabs, v0.1.7
git-log, v0.4.1
linter, v1.11.3
project-manager, v2.7.5
terminal-plus, v0.14.5
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by kankaristo** [comment]
Got this today with Atom 1.5.0-beta1, when closing the last tab in a pane (destroying the pane).

**Atom Version**: 1.5.0-beta1
**System**: Ubuntu 15.10
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0


### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At /usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24

TypeError: Cannot read property 'forEach' of undefined
    at module.exports.CompositeDisposable.dispose (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:25)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.destroyed (/usr/share/atom-beta/resources/app.asar/src/pane.js:659:20)
    at Pane.module.exports.Model.destroy (/usr/share/atom-beta/resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/usr/share/atom-beta/resources/app.asar/src/pane.js:650:39)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:422:21)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom-beta/resources/app.asar/src/pane.js:464:16)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom-beta/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:677:19)
```

**Comment by jhicken** [comment]
I am also getting this issue.

My steps to reproduce this are.
1. Install https://github.com/littlebee/git-time-machine
2. run `Git Time Machine: Toggle`
3. close the diff pane on the right side of the editor

4. bask in the brokeness of the editor. / profit

Let me know if you need more info.

I would dig deeper but I don't have time at the moment.

**Comment by benogle** [comment]
@kankaristo does this happen all the time for you? Can you try starting atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

My hunch is that some package is putting returning an undefined to some function that is putting the return value in a composite disposable.

**Comment by kankaristo** [comment]
@benogle, happens every time, but not in safe mode.

The culprit seems to be [foldername-tabs](https://atom.io/packages/foldername-tabs), which was updated 2 days ago. I'll open an issue there.

**Comment by kankaristo** [comment]
I'm not getting theerror anymore, after updating foldername-tabs to version 0.1.9 (released a few hours ago).

**Comment by 50Wliu** [comment]
Closing since @Manabu-Shirato also had foldername-tabs installed, and the latest version seems to fix the issue.

**Comment by benogle** [comment]
Imma reopen this as I think it's something we should guard against in core.
