### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by duboff** [atom/tabs#254]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught TypeError: Cannot read property 'isValid' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:665

TypeError: Cannot read property 'isValid' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateOverlaysState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:665:36)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:166:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:183:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:195:38)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:278:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:933:16)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:95:22)
    at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:165:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:175:19)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:223:19)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:188:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:231:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:648:20)
    at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:639:39)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:411:21)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:453:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
 34x -9:05.5.0 core:close (atom-text-editor.editor.is-focused)
  2x -8:38.6.0 pane:split-up (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-centurion-ui)
  2x -8:12.5.0 pane:split-right (atom-text-editor.editor.is-focused)
     -6:50 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:46.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:54.9.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-centurion-ui)
     -1:06.1.0 ruby-test:test-file (atom-text-editor.editor.is-focused)
     -0:50.3.0 rspec:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-elixir",
      "linter-rails-best-practices",
      "rails-rspec"
    ],
    "themes": [
      "centurion-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, v0.28.21
autoclose-html, v0.20.0
autocomplete-ruby, v0.1.0
build-elixir, v0.6.0
centurion-ui, v0.5.0
elixir-cmd, v0.2.9
ember-cli-helper, v0.9.0
ember-tabs, v2.2.0
iex, v0.9.23
language-elixir, v0.8.0
language-graphql, v0.2.0
linter, v1.11.3
linter-csslint, v1.2.0
linter-elixirc, v1.1.5
linter-golinter, v1.1.0
linter-rubocop, v0.4.7
linter-sass-lint, v1.0.3
open-recent, v5.0.0
rspec, v0.3.2
ruby-syntax-replacer, v0.5.1
ruby-test, v0.9.17

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @duboff, what were you doing when this occurred?

**Comment by duboff** [comment]
Hi @50Wliu, I am not quite sure. I think just tried opening multiple panes and searching. Was my first time using Atom. Sorry, but can't provide more context.
