### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItems' of undefined

### ISSUE THREAD

**Issue by rekurt** [atom/tabs#257]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: elementary OS
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getItems' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:613

TypeError: Cannot read property 'getItems' of undefined
    at atom-tabs.TabBarView.onDrop (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:613:24)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.5.0
atom-autocomplete-php, v0.18.7
color-picker, v2.1.1
drunken-php, v0.2.1
emmet, v2.4.1
emmet-simplified, v2.5.0
emmet-snippets-compatibility, v1.0.4
hyperclick-php, v0.2.1
jQuery, v1.2.1
jquery-snippets, v11.0.0
livestyle-atom, v0.1.2
minimap, v4.19.0
robin-language-php, v0.9.0

# Dev
No dev packages
```

**Comment by Misiak4** [comment]
[Enter steps to reproduce below:]

1. Open two windows
2. Move tab from one window to another

**Atom Version**: 1.12.0
**Electron Version**: 1.3.6
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.103.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getItems' of undefined

```
At C:\Users\Michal\AppData\Local\atom\app-1.12.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:624

TypeError: Cannot read property 'getItems' of undefined
    at atom-tabs.TabBarView.onDrop (C:\Users\Michal\AppData\Local\atom\app-1.12.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:624:24)
```

### Commands

```
     -3:34.3.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -3:34 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:49.7.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:01.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "remote-sync",
      "php-integrator-refactoring",
      "autohide-tree-view"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
aligner-php, v1.0.0 (active)
atom-beautify, v0.29.13 (active)
autohide-tree-view, v0.25.1 (inactive)
language-blade, v0.26.2 (active)
laravel, v0.7.0 (active)
linter, v1.11.18 (active)
linter-php, v1.3.1 (active)
minimap, v4.25.6 (active)
minimap-autohide, v0.10.1 (active)
php-cs-fixer, v2.5.9 (active)
php-integrator-annotations, v1.0.3 (active)
php-integrator-autocomplete-plus, v1.1.5 (active)
php-integrator-base, v1.2.6 (active)
php-integrator-call-tips, v1.1.1 (active)
php-integrator-navigation, v1.0.3 (active)
php-integrator-refactoring, v1.1.1 (inactive)
php-integrator-tooltips, v1.0.4 (active)
project-manager, v3.3.3 (active)
Remote-FTP, v0.9.4 (active)
split-diff, v1.0.6 (inactive)
sync-settings, v0.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.0 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.3 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by nickolasclarke** [comment]
@Misiak4 ftw, I was experiencing the same, but as of Atom 1.12.3, this seems to be resolved.

**Comment by sounakban** [comment]
I have version 1.13.0, and I am getting the same error.
I am running on Ubuntu 16.04LTS.

**Comment by rsese** [comment]
@sounakban 1.16.0 was just released today, can you update and let us know if you still see this error?  And if so, please share steps to reproduce and let us know if you can reproduce in safe mode (`atom --safe`) - thanks!

**Comment by sounakban** [comment]
The issue is resolved.
Thank you.

**Comment by rsese** [comment]
@michalurva or @rekurt, are either of you able to reproduce this error now after upgrading to 1.16.0?

**Comment by rsese** [comment]
@c0fe - I see you ran into this issue in 1.16.0 from your issue in https://github.com/atom/atom/issues/14462.  Is the error reproducible for you?

**Comment by c0fe** [comment]
@rsese I am trying but I think my issue is more of an edge case. It does happen from time to time and I am not sure what triggers it. I am trying to go back and see if I can figure out how it happens. I know the behavior of it.

Say, I have one file already open, then I go back to Explorer and select another file to be open through context menu (which how I open them all), it will on its own open in a new window and when I try to drag it in, then I get the error I got.

**Comment by ahogen** [comment]
I just got this error. I double-clicked a Markdown file in Explorer which opened up the file in a new Atom window. I already had an existing Atom window up. I attempted to drag the Markdown tab in the new atom window to the old/original Atom window, like you might do it Chrome to merge tabs into the same window. This error popped up when release my mouse (dropping the tab).

Basically, this looks very similar to what @c0fe [is describing](https://github.com/atom/tabs/issues/257#issuecomment-302445404).

```
Uncaught TypeError: Cannot read property 'getItems' of undefined
....\atom\app-1.17.2\resources\app\node_modules\tabs\lib\tab-bar-view.js:641

Hide Stack Trace
TypeError: Cannot read property 'getItems' of undefined
    at TabBarView.module.exports.TabBarView.onDrop (....\atom\app-1.17.2\resources\app\node_modules\tabs\lib\tab-bar-view.js:641:1)
```

## Environment
- Atom 1.17.2 x64
- Windows 7 Professional x64

#### Packages (community)
- atom-clock
- autoclose-html
- docblockr
- file-type-icons
- highlight-selected
- package-sync
- svn

**Comment by rsese** [comment]
Hmm, one difference I noticed is that you both mentioned that you have a window open and then opening a file from Explorer opens a new Atom window.  For me, if I have Atom open, opening a new file from Explorer will open the file as a tab in the existing window.

**Comment by c0fe** [comment]
@rsese this varies from time to time, sometimes it opens a new tab and sometimes it opens a new window.

**Comment by sknorr** [comment]
I can reproduce both the two-window behavior and the original issue on Atom 1.18/Linux: For me, Atom always opens two windows when starting Atom and opening two files in quick succession (you open the second file while Atom is still starting), e.g.
1. first make sure Atom is closed
2. do from the command line: `atom file1 && atom file2`. (Of moderate interest: using `;` instead of `&&`, I can't reproduce this.)

When I then try to move one of the tabs to another window, I get the original error.

**Comment by Ben3eeE** [comment]
I can reproduce this on Windows 7 with Atom 1.19.0-beta7 with the steps @sknorr provided.

I made two files `file1` and `file2` and started atom from `cmd.exe` using `atom --safe file && atom --safe file2`. Two Atom windows open and when moving either of the tabs between the windows this exception is thrown.

**Comment by rsese** [comment]
Hmm, I still can't reproduce the two windows opening but I'll tag as triaged since you can repro @Ben3eeE :+1:

I also added your steps to repro @sknorr in the issue body (just added the `--safe` flags).

**Comment by Ben3eeE** [comment]
@rsese I just tested on my home computer which is Windows 10 and has better performance and I can't reproduce the two windows opening. On my work computer I reproduced it several times.

**Comment by ak0la** [comment]
I just had this error on my work pc. 
it's a i7 workstation running a pretty fresh install of Windows 10, Atom version 1.33.1 and tabs 0.109.2
I have some other packages installed like linter, highlight-selected, busy-signal...
I had probably close to 20 tabs in one window and 20 in the other. 
Hope that helps ya track down the pesky bug.
Great work on Atom btw

**Comment by ak0la** [comment]
[Enter steps to reproduce:]

1. open the same large project in two windows
2. maximize one window
3. open about twenty tabs of code in each window
4. drag one open tab over to the other window and try to place it between the tabs

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'getItems' of undefined

```
At C:\Users\lmr\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11

TypeError: Cannot read property 'getItems' of undefined
    at TabBarView.t.exports.TabBarView.onDrop (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1140229)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.0 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
```
