### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'C:\Users\Kirill\Documents\TMKWeb\TMKWeb.Web\Scripts\...

### ISSUE THREAD

**Issue by kirsanv43** [atom/tabs#258]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Unknown Windows Version
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\Kirill\Documents\TMKWeb\TMKWeb.Web\Scripts\reactApp\app\components\DefinitionNode.jsx' that has already been destroyed

```
At C:\Users\Kirill\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:331

Error: Adding a pane item with URI 'C:\Users\Kirill\Documents\TMKWeb\TMKWeb.Web\Scripts\reactApp\app\components\DefinitionNode.jsx' that has already been destroyed
    at Pane.module.exports.Pane.addItem (C:\Users\Kirill\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:331:15)
    at Pane.module.exports.Pane.activateItem (C:\Users\Kirill\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:315:14)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\Kirill\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```

### Commands

```
  5x -2:19.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:16.7.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:16.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:16.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:12.9.0 core:copy (atom-text-editor.editor.is-focused)
     -2:10.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:50.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:45.1.0 core:copy (atom-text-editor.editor.is-focused)
  2x -1:44.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:30.7.0 tabs:close-other-tabs (div.title)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-typescript"
    ],
    "themes": [
      "seti-ui",
      "an-old-hope-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0
atom-beautify, v0.28.21
atom-ternjs, v0.13.2
autocomplete-paths, v1.0.2
emmet, v2.4.1
file-icons, v1.6.14
linter, v1.11.3
react, v0.14.1
react-snippets, v0.3.0
seti-ui, v0.8.1
sublime-panes, v0.2.5

# Dev
No dev packages
```

**Comment by wylie** [comment]
I'm also getting this error.

--- 

## Uncaught Error: Adding a pane item with URI '/Users/wfisher/Repos/resources/st4/includes/scss/p...

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.92.0


### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/wfisher/Repos/resources/st4/includes/scss/partials/desktop/cms/_ideas_header.scss' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:453

Error: Adding a pane item with URI '/Users/wfisher/Repos/resources/st4/includes/scss/partials/desktop/cms/_ideas_header.scss' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:453:15)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:428:14)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:628:19)
```

### Commands

```
  4x -0:48 core:close (atom-text-editor.editor.is-focused.power-mode)
  4x -0:44.3.0 pane:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:37.2.0 pane:split-down (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:35.3.0 pane:close (atom-pane.pane.active)
     -0:21 tree-view:reveal-active-file (li.texteditor.tab.sortable.active.right-clicked)
     -0:17 tree-view:copy-project-path (span.name.icon.icon-file-text)
     -0:16.1.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.6.0 pane:close (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false
  },
  "tabs": {
    "addNewTabsAtEnd": true,
    "enableVcsColoring": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atom-beautify, v0.29.7
atom-shortcuts, v0.0.2
file-icons, v1.7.11
highlight-selected, v0.11.2
minimap, v4.23.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-pigments, v0.2.1
open-recent, v5.0.0
pigments, v0.26.3
project-manager, v2.9.7

# Dev
No dev packages
```
