### ISSUE TITLE
Uncaught Error: Undefined screen line when clipping screen position

### ISSUE THREAD

**Issue by supaiku0** [atom/tabs#261]
[Enter steps to reproduce below:]
1. Close a bunch of files which got deleted on FS
2. Click Don't Save on each message
3. Eventually the error is reproduced

**Atom Version**: 1.5.3
**System**: linux 4.3.5-1-ck
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.88.0
### Stack Trace

Uncaught Error: Undefined screen line when clipping screen position

```
At /usr/share/atom/resources/app.asar/src/display-buffer.js:886

Error: Undefined screen line when clipping screen position
    at DisplayBuffer.module.exports.DisplayBuffer.clipScreenPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:874:15)
    at DisplayBuffer.module.exports.DisplayBuffer.bufferPositionForScreenPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:826:20)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor-marker.js:185:60)
    at /usr/share/atom/resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app.asar/src/cursor.js:673:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/usr/share/atom/resources/app.asar/src/cursor.js:65:19)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:1476:23
    at TextEditor.module.exports.TextEditor.moveCursors (/usr/share/atom/resources/app.asar/src/text-editor.js:1680:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1475:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/usr/share/atom/resources/app.asar/src/text-editor-component.js:704:25)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)
    at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at Object.RemoteMemberFunction [as showMessageBox] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ApplicationDelegate.module.exports.ApplicationDelegate.confirm (/usr/share/atom/resources/app.asar/src/application-delegate.js:201:23)
    at Pane.module.exports.Pane.promptToSaveItem (/usr/share/atom/resources/app.asar/src/pane.js:510:41)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:463:18)
    at atom-tabs.TabBarView.closeTab (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:384:26)
    at atom-tabs.TabBarView.closeAllTabs (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:464:28)
    at Object.addElementCommands.tabs:close-all-tabs (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:107:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:78:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:12.5.0 tabs:close-all-tabs (li.tab.sortable.right-clicked)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.22
release-notes, v0.53.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further reports.
