### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'C:\Users\Enda\Documents\Web Dev 2015\Node\5-nodejs-e...

### ISSUE THREAD

**Issue by EndaMoore** [atom/tabs#290]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.91.3

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\Enda\Documents\Web Dev 2015\Node\5-nodejs-express-web-applications-m5-exercise-files\codeStart\library\src\views\index.ejs' that has already been destroyed

```
At C:\Users\Enda\AppData\Local\atom\app-1.6.0\resources\app.asar\src\pane.js:358

Error: Adding a pane item with URI 'C:\Users\Enda\Documents\Web Dev 2015\Node\5-nodejs-express-web-applications-m5-exercise-files\codeStart\library\src\views\index.ejs' that has already been destroyed
    at Pane.module.exports.Pane.addItem (C:\Users\Enda\AppData\Local\atom\app-1.6.0\resources\app.asar\src\pane.js:358:15)
    at Pane.module.exports.Pane.activateItem (C:\Users\Enda\AppData\Local\atom\app-1.6.0\resources\app.asar\src\pane.js:333:14)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\Enda\AppData\Local\atom\app-1.6.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:592:19)
```

### Commands

```
     -5:31.6.0 pane:split-right (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -5:26.7.0 window:toggle-full-screen (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:13.1.0 pane:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:29.6.0 pane:split-right (atom-text-editor.editor.is-focused)
     -3:56 pane:split-up (atom-text-editor.editor.is-focused)
     -3:48.4.0 pane:split-down (atom-pane.pane.active)
  2x -3:39.5.0 window:focus-previous-pane (atom-pane.pane.active)
  2x -2:33.8.0 pane:close (li.tab.sortable.active.right-clicked)
     -2:11.5.0 window:focus-previous-pane (atom-pane.pane.active)
     -2:02.6.0 settings-view:open (atom-pane.pane.active)
     -1:55.9.0 window:focus-next-pane (atom-pane.pane.active)
     -1:45.9.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -1:40.5.0 pane:split-up (ul.list-inline.tab-bar.inset-panel)
     -1:36.3.0 pane:close (ul.list-inline.tab-bar.inset-panel)
     -0:17.9.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -0:12.2.0 pane:split-up (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint"
    ],
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.2.9
atom-terminal, v0.8.0
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.6.18
highlight-line, v0.11.1
highlight-selected, v0.11.2
pigments, v0.25.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Closing in favor of #258.
