### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of null

### ISSUE THREAD

**Issue by LestaD** [atom/tabs#309]
1. Open any file 
2. Enter command `Open in` Press Enter

**Atom Version**: 1.7.2
**System**: elementary OS
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.92.0

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of null

```
At /usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:320

TypeError: Cannot read property 'item' of null
    at atom-tabs.TabBarView.openInNewWindow (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:320:17)
    at atom-pane.subscriptions.add.atom.commands.add.tabs:open-in-new-window (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:73:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:36.2.0 command-palette:toggle (div.package-detail.panels-item)
     -0:35.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:35.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:34.6.0 fuzzy-finder:toggle-file-finder (div.package-detail.panels-item)
     -0:32.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:32.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:32.3.0 command-palette:toggle (div.package-detail.panels-item)
     -0:28.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.2.0 tabs:open-in-new-window (div.package-detail.panels-item)
     -0:16.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.8.0 tabs:open-in-new-window (atom-text-editor.editor)
     -0:08.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:05.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 tabs:open-in-new-window (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "npm",
      "language-gfm",
      "git-status"
    ],
    "exception-reporting": {
      "userId": "ee573c4a-655e-52fa-1f4f-24c6f9b1ba2b"
    },
    "projectHome": "/Users/lestad/projects",
    "userId": "ee573c4a-655e-52fa-1f4f-24c6f9b1ba2b"
  }
}
```

### Installed Packages

```md
# User
Stylus, v3.0.0
atom-jade, v0.3.0
autocomplete-modules, v1.4.1
bottom-dock, v0.4.4
gulp-manager, v0.2.19
language-babel, v2.17.3
language-gitignore, v0.2.0
language-markdown, v0.12.0
language-nginx, v0.6.1
language-rust, v0.4.6
node-debugger, v1.4.7
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Your repro steps don't really make sense. Where are you typing the command "Open in"?

**Comment by tomaso** [comment]
I get the same error when I open the "Command pallete" and try the "Open in" (would be completed as "Tabs: open in new window").
It's actually recorded in the "video" in README.md of project-manager: https://github.com/danielbrodin/atom-project-manager

**Comment by lee-dohm** [comment]
Thanks @tomaso :grinning:
