### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by arca1405** [atom/tabs#315]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 14.04.4
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.92.0
### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
    at GutterContainer.module.exports.GutterContainer.onDidAddGutter (/usr/share/atom/resources/app.asar/src/gutter-container.js:81:27)
    at TextEditor.module.exports.TextEditor.onDidAddGutter (/usr/share/atom/resources/app.asar/src/text-editor.js:539:35)
    at TextEditorPresenter.module.exports.TextEditorPresenter.observeModel (/usr/share/atom/resources/app.asar/src/text-editor-presenter.js:207:39)
    at new TextEditorPresenter (/usr/share/atom/resources/app.asar/src/text-editor-presenter.js:49:12)
    at new TextEditorComponent (/usr/share/atom/resources/app.asar/src/text-editor-component.js:114:24)
    at atom-text-editor.TextEditorElement.mountComponent (/usr/share/atom/resources/app.asar/src/text-editor-element.js:222:24)
    at atom-text-editor.TextEditorElement.attachedCallback (/usr/share/atom/resources/app.asar/src/text-editor-element.js:99:14)
    at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activateNextItem (/usr/share/atom/resources/app.asar/src/pane.js:369:21)
    at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:562:16)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:17)
```
### Commands

```
     -0:34.2.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @arca1405, what were you doing when this error occurred?

**Comment by wordsoup** [comment]
I've also received this error today:
Steps to Reproduce
- Closed multiple (3) tabs of .md files in cloned repo in Atom. MD Preview Tab was also open.
- After closing last tab, error appeared.
- Github Desktop was also running.

Atom Version: 1.8.0
OS: OS X El Capitan 10.11.5

`Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
    at GutterContainer.module.exports.GutterContainer.onDidAddGutter (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:81:27)
    at TextEditor.module.exports.TextEditor.onDidAddGutter (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:539:35)
    at TextEditorPresenter.module.exports.TextEditorPresenter.observeModel (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:207:39)
    at new TextEditorPresenter (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:49:12)
    at new TextEditorComponent (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:114:24)
    at atom-text-editor.TextEditorElement.mountComponent (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:222:24)
    at atom-text-editor.TextEditorElement.attachedCallback (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:99:14)
    at atom-pane.PaneElement.activeItemChanged (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activatePreviousItem (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:379:21)
    at Pane.module.exports.Pane.removeItem (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:564:16)
    at Pane.module.exports.Pane.destroyItem (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/Users/wordsoup/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)`

`The error was thrown from the tabs package.`
