### ISSUE TITLE
Uncaught TypeError: this.iconName.split is not a function

### ISSUE THREAD

**Issue by planvin** [atom/tabs#328]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.96.0

### Stack Trace

Uncaught TypeError: this.iconName.split is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:325

TypeError: this.iconName.split is not a function
    at tabs-tab.module.exports.TabView.updateIcon (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:325:63)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:123:24
    at HTMLEditor.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/emissary/lib/emitter.js:118:15)
    at HTMLEditor.module.exports.HTMLEditor.updateIcon (/Users/pierre/.atom/packages/browser-plus/lib/browser-plus-model.coffee:69:8)
    at webview.<anonymous> (/Users/pierre/.atom/packages/browser-plus/lib/browser-plus-view.coffee:233:16)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:188:29)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/guest-view-internal.js:56:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/guest-view-internal.js:67:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -1:40.8.0 command-palette:toggle (atom-pane.pane.active)
     -1:38.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:37.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:37.4.0 browser-plus:open (atom-pane.pane.active)
     -1:12.7.0 pane:split-right (atom-pane.pane.active)
     -0:47.5.0 jekyll:toggle-server (input#uri.native-key-bindings.ui-autocomplete-input)
  2x -0:32.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
browser-plus, v0.0.60
jekyll, v1.4.1
language-liquid, v0.5.1
language-scala, v1.1.6
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to skandasoft/browser-plus#75
