### ISSUE TITLE
init.coffee Uncaught ReferenceError: file is not defined

### ISSUE THREAD

**Issue by Gnafu** [atom/tabs#338]
I was just blindly copy-pasting this thread
https://discuss.atom.io/t/how-to-show-full-path-in-atom-title/8296/26
1. Open init.coffee with Atom
2. Edit and save
3. Close Atom -> Atom crashes
4. Revert the init.coffee script (empty or all commented)
5. Atom still crashes every time it is closed.

**Atom Version**: 1.7.4
**System**: Windows 8.1
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.96.0
### Stack Trace

Uncaught ReferenceError: file is not defined

```
At /C:/Users/REDACTED/.atom/init.coffee:12

ReferenceError: file is not defined
    at TextEditor.editor.getTitle (file:///C:/Users/REDACTED/.atom/init.coffee:19:30)
    at tabs-tab.module.exports.TabView.updateTitle (C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\tabs\lib\tab-view.js:299:27)
    at atom-tabs.TabBarView.removeTabForItem (C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:264:13)
    at C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:178:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\src\pane.js:568:20)
    at Pane.module.exports.Pane.destroyItem (C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\src\pane.js:637:16)
    at atom-tabs.TabBarView.onClick (C:\Users\REDACTED\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:688:17)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
editorconfig, v1.4.1
highlight-selected, v0.11.2
linter, v1.11.4
linter-eslint, v7.2.2
react, v0.15.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This is definitely an issue with your init script.  To make sure you have fully reverted it, you can delete `init.coffee`.  Atom will regenerate it on next launch.
