### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '...

### ISSUE THREAD

**Issue by janosimas** [atom/tabs#372]
[Enter steps to reproduce below:]

I'm using the tabasco package to move tabs.
I dragged a tab to the side of the screen to split the pane.
The exception was raised but everything worked as expected.

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Ubuntu 14.04.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.100.2

### Stack Trace

Uncaught Error: Adding a pane item with URI '/path/to/file.cpp' that has already been destroyed

```
At /opt/atom/resources/app.asar/src/pane.js:455

Error: Adding a pane item with URI '/path/to/file.cpp' that has already been destroyed
  at Pane.module.exports.Pane.addItem (/opt/atom/resources/app.asar/src/pane.js:455:15)
  at Pane.module.exports.Pane.moveItemToPane (/opt/atom/resources/app.asar/src/pane.js:612:19)
  at Object.module.exports.end (/opt/atom/resources/app.asar/node_modules/tabs/lib/layout.js:60:16)
  at tabs-tab.ondragend (/opt/atom/resources/app.asar/node_modules/tabs/lib/tab-view.js:54:23)

```

### Commands

```
     -2:22 tree-view:toggle (div.terminal-plus.status-bar)
     -0:40.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:39.9.0 core:cut (atom-text-editor.editor.is-focused)
  3x -0:39.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:38.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:38.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:38 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:38 snippets:expand (atom-text-editor.editor.is-focused)
     -0:37.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:35.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:33.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:32.1.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:31.8.0 core:delete (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter-clang"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.65.0 (active)
build-cmake, v0.6.3 (active)
busy, v0.6.0 (active)
file-type-icons, v1.3.2 (active)
formatter, v2.12.3 (active)
formatter-astyle, v1.0.0 (active)
git-log, v0.4.1 (active)
git-plus, v5.16.2 (inactive)
highlight-selected, v0.11.2 (active)
language-cmake, v0.2.0 (active)
language-cpp14, v0.6.2 (active)
language-pgsql, v0.2.3 (active)
language-qtpro, v0.6.0 (active)
language-valgrind, v0.1.0 (active)
linter, v1.11.16 (active)
linter-clang, v3.4.4 (inactive)
linter-cppcheck, v0.2.0 (active)
nuclide, v0.166.0 (active)
open-recent, v5.0.0 (active)
pdf-view, v0.50.0 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
symbol-gen, v1.3.1 (active)
tabasco, v0.5.0 (active)
terminal-plus, v0.14.5 (active)
todo-show, v1.7.0 (inactive)
tomatimer, v1.2.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by janosimas** [comment]
Maybe so, I used the atom git issue suggestion but...
This started with the atom 1.10.0 update, no update of tabasco.

**Comment by Ben3eeE** [comment]
The core tabs package provide drag and drop layout management functionality now which maybe causes a conflict?

**Comment by janosimas** [comment]
Looks like I don't need tabasco anymore :-)
no issues with tabs package.

should I close the issue?
