### ISSUE TITLE
Uncaught TypeError: Cannot read property 'moveItemToPane' of undefined

### ISSUE THREAD

**Issue by mh-cbon** [atom/tabs#387]
[Enter steps to reproduce below:]

1. installed term3 package
2. open settings page
2. open new terminal with ctrl alt t
3. drag pane tab to split panes horizontally

did not work as expected, it split vertically, got this message, i had one pane with empty content in it (no file, no setting page, blank)

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: "Fedora release
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.101.0

### Stack Trace

Uncaught TypeError: Cannot read property 'moveItemToPane' of undefined

```
At /home/travis/build/atom/atom/out/app/node_modules/tabs/lib/layout.coffee:60

TypeError: Cannot read property 'moveItemToPane' of undefined
    at Object.module.exports.end (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/layout.js:60:15)
    at tabs-tab.ondragend (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-view.js:54:23)
```

### Commands

```
     -0:24.8.0 pane:reopen-closed-item (p.text.icon.icon-dashboard.native-key-bindings)
     -0:08.4.0 term3:open (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "minimap",
      "atom-terminal-panel",
      "terminal-plus"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0 (inactive)
atom-terminal-panel, v4.4.4 (inactive)
language-riot-tag, v0.2.2 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (inactive)
pigments, v0.37.0 (active)
term3, v0.22.1 (active)
terminal-plus, v0.14.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (active)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
This sounds like a problem with the term3 package. Please file the issue there instead.
