### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Documents/projects/k_kristiansen_1510/slurm-532043...

### ISSUE THREAD

**Issue by rasmusagren** [atom/tabs#393]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.101.0

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/arasmus/Documents/projects/k_kristiansen_1510/slurm-532043.out' that has already been destroyed

```
At /Users/distiller/atom/out/app/src/pane.coffee:459

Error: Adding a pane item with URI '/Users/arasmus/Documents/projects/k_kristiansen_1510/slurm-532043.out' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:459:15)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:434:14)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:662:19)
```

### Commands

```
     -1:03.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:02.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:01.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:01.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:01.5.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:59 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:55.5.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:54.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:53.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:53 core:save (atom-text-editor.editor.is-focused)
     -0:07.0 remote-ftp:refresh-selected (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "spell-check"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "Thumbs.db",
      ".DS_Store",
      "._*",
      ".Rhistory"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-types, v0.5.4-p1 (active)
git-plus, v5.18.0 (active)
github-atom-light-syntax, v0.2.0 (inactive)
Hydrogen, v0.15.0 (inactive)
language-docker, v1.1.7 (active)
language-r, v0.4.1 (active)
pane-manager, v1.0.1 (active)
pdf-view, v0.50.0 (inactive)
platformio-ide-terminal, v2.2.0 (active)
project-manager, v3.2.5 (active)
Remote-FTP, v0.9.0 (active)
remote-sync, v4.1.4 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Looks like this may be a bug in the [remote-ftp](https://github.com/mgrenier/remote-ftp) package - please report this issue over there instead.  Thanks!
