### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/home/vageesh/git/hello-world/README.md'

### ISSUE THREAD

**Issue by vageeshkulkarni** [atom/tabs#407]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.5.0-54-generic
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.61.0

### Stack Trace

Uncaught Error: EACCES, permission denied '/home/vageesh/git/hello-world/README.md'

```
At /usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:311

Error: EACCES, permission denied '/home/vageesh/git/hello-world/README.md'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/usr/share/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:227:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:297:21)
  at File.module.exports.File.write (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:286:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:966:17)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:589:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.promptToSaveItem (/usr/share/atom/resources/app/src/pane.js:490:23)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:442:18)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -30:26.9 core:delete (atom-text-editor.editor)
     -30:25.7 editor:newline (atom-text-editor.editor)
     -30:23.3 core:paste (atom-text-editor.editor)
  5x -30:00.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Please update Atom - you are more than 50 minor releases behind.
