### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/Applications/Atom.app/Contents/Resources/app/node_modules/welcome/docs/darwin/welcome.md'

### ISSUE THREAD

**Issue by JessSchoon** [atom/tabs#417]
Uncaught Error: EACCES, permission denied '/Applications/Atom.app/Contents/Resources/app/node_modules/welcome/docs/darwin/welcome.md'

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.57.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:308

Error: EACCES, permission denied '/Applications/Atom.app/Contents/Resources/app/node_modules/welcome/docs/darwin/welcome.md'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:227:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:297:21)
  at File.module.exports.File.write (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:286:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:966:17)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:490:23)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:442:18)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at Object.RemoteMemberFunction [as showMessageBox] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:680:23)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:483:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:442:18)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at Object.RemoteMemberFunction [as showMessageBox] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:680:23)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:483:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:442:18)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:174:22)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

/cc @atom/core

**Comment by Ben3eeE** [comment]
> Atom Version: 0.158.0

This is an ancient Atom version. Please update to the latest version and submit a new issue if you are still experiencing this.
