### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setFlexScale' of undefined

### ISSUE THREAD

**Issue by pencilcheck** [atom/tabs#430]
[Enter steps to reproduce:]

1. Was opening and closing panes

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.104.1

### Stack Trace

Uncaught TypeError: Cannot read property 'setFlexScale' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:222

TypeError: Cannot read property 'setFlexScale' of undefined
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/app.asar/src/pane-axis.js:222:16)
    at PaneAxis.module.exports.PaneAxis.removeChild (/app.asar/src/pane-axis.js:188:21)
    at /app.asar/src/pane-axis.js:231:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.destroyed (/app.asar/src/pane.js:875:20)
    at Pane.module.exports.Model.destroy (/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/app.asar/src/pane.js:866:39)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:605:21)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
  2x -1:59.1.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -1:56.8.0 settings-view:open (input.hidden-input)
     -1:54.9.0 editor:consolidate-selections (input.hidden-input)
     -1:54.9.0 core:cancel (input.hidden-input)
     -1:45.2.0 settings-view:open (input.hidden-input)
  2x -1:44.6.0 key-binding-resolver:toggle (input.hidden-input)
     -1:40.5.0 window:focus-pane-on-left (input.hidden-input)
     -1:39.9.0 window:focus-pane-on-right (input.hidden-input)
     -1:38.3.0 paner:very-top (input.hidden-input)
     -1:37.7.0 vim-mode-plus:move-down (input.hidden-input)
     -1:37.4.0 vim-mode-plus:move-up (input.hidden-input)
     -1:36.7.0 paner:very-left (input.hidden-input)
 10x -1:36.1.0 vim-mode-plus:move-down (input.hidden-input)
     -0:28.1.0 settings-view:open (input.hidden-input)
     -0:26.6.0 core:select-all (input.hidden-input)
  3x -0:26.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
color-picker 2.2.5 
cursor-history 0.9.1 
fizzy 0.21.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.3.3 
intentions 1.1.2 
language-elm 1.5.0 
linter 2.1.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.2 
merge-conflicts 1.4.4 
minimap 4.27.0 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
monokai 0.22.0 
open-this 0.4.0 
paner 0.4.0 
pigments 0.39.1 
qolor 0.4.1 
rainbow-selection-flux 1.2.0 
vim-mode-plus 0.85.1 
vim-mode-plus-ex-mode 0.9.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-selected-text 0.9.0 
wombat 1.0.4 
zenburn 3.1.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, do you see the error in safe mode (atom --safe)?

**Comment by pencilcheck** [comment]
I'm not sure. I just happen randomly when I was playing around the panels and resizing and closing them.

**Comment by rsese** [comment]
Thanks - if you can reliably reproduce the error with specific steps, please let us now :v:
