### ISSUE TITLE
Uncaught Error: Cannot get property 'id' on missing remote object 84Error: Cannot get property '...

### ISSUE THREAD

**Issue by Permutatrix** [atom/tabs#449]
I have no idea what I did to cause this. It happened when I was switching tabs. The session had been open for a while, and I'd done plenty of tab-switching previously. Aside from the error message, nothing appears out of the ordinary.

**Atom**: 1.17.2 x64
**Electron**: 1.4.16
**OS**: "Arch Linux"
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Cannot get property 'id' on missing remote object 84
Error: Cannot get property 'id' on missing remote object 84
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:368:7)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217

Error: Cannot get property 'id' on missing remote object 84
Error: Cannot get property 'id' on missing remote object 84
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:368:7)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.descriptor.get [as id] (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:131:16)
    at TabBarView.module.exports.TabBarView.getWindowId (/usr/lib/atom/node_modules/tabs/lib/tab-bar-view.js:472:93)
    at TabBarView.module.exports.TabBarView.onDragStart (/usr/lib/atom/node_modules/tabs/lib/tab-bar-view.js:493:57)
```

### Commands

```
     -2:29.3.0 core:copy (input.hidden-input)
     -2:26.5.0 intentions:highlight (input.hidden-input)
     -2:26.5.0 core:paste (input.hidden-input)
  2x -2:18.7.0 core:backspace (input.hidden-input)
     -2:15.4.0 intentions:highlight (input.hidden-input)
     -2:15 editor:outdent-selected-rows (input.hidden-input)
  2x -2:10.4.0 core:backspace (input.hidden-input)
     -2:00.7.0 intentions:highlight (input.hidden-input)
     -2:00.7.0 core:cut (input.hidden-input)
     -1:59.9.0 core:backspace (input.hidden-input)
     -1:59.5.0 core:move-up (input.hidden-input)
     -1:59.1.0 editor:newline (input.hidden-input)
     -1:58.8.0 intentions:highlight (input.hidden-input)
     -1:58.8.0 core:paste (input.hidden-input)
     -1:57.3.0 intentions:highlight (input.hidden-input)
     -1:57.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-handlebars 1.3.0 
atom-typescript 11.0.3 
busy-signal 1.4.1 
haxe 0.8.14 
intentions 1.1.2 
language-babel 2.65.1 
language-ebnf 0.1.0 
language-haxe 0.6.0 
language-latex 1.0.0 
language-liquid 0.5.1 
language-lua 0.9.11 
language-markdown 0.22.0 
language-nunjucks 4.1.0 
language-rust 0.4.10 
linter 2.1.4 
linter-rust 0.8.0 
linter-ui-default 1.6.0 
markdown-document 0.2.1 
markdown-scroll-sync 2.1.2 
minimap 4.28.2 
monokai-blue-syntax 0.0.0 
racer 0.20.0 
```

**Comment by rsese** [comment]
> Electron: 1.4.16

> Electron: 1.4.16

Thanks for reaching out!

We've determined that you are using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).  If you can still reproduce the problem on an official distribution of Atom, please feel free to create a new issue.
