### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by MacroMachines** [atom/tabs#483]
[Enter steps to reproduce:]

1. close the last tab, which was the atom welcome tab...
2. orange bug window pops up and takes me here...
... atom is amazing.....

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:872

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:872:21)
    at PaneContainer.activateNextPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:198:30)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app/src/pane.js:893:32)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:629:27)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:685:22)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:340:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:228:25)
```

### Commands

```
     -8:16.2.0 core:backspace (input.hidden-input)
     -7:20.2.0 core:confirm (input.hidden-input)
  4x -1:28.3.0 core:backspace (div.package-detail.panels-item)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
build 0.68.0 
busy 0.7.0 
exoshader 0.5.0 
file-icons 2.1.7 
glsl-preview 0.13.0 
hyperclick 0.1.2 
hyperclick-love 0.6.0 
intentions 1.1.2 
language-glsl 2.0.1 
language-ini 1.19.0 
language-lua 0.9.11 
linter 2.2.0 
linter-gcc 0.7.1 
linter-glsl 2.1.3 
linter-luaparse 0.2.0 
linter-ui-default 1.6.1 
love-ide 0.17.0 
minimap 4.28.2 
platformio-aia 0.0.5 
platformio-ide 2.0.0-beta.7 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
termination 0.5.1 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, is it reproducible in safe mode (atom --safe)?

**Comment by robertopc** [comment]
[Enter steps to reproduce:]

1. Create a markdown file and open preview with package Markdown Preview Plus 2.4.10
2. Close markdown file and reopen
3. Click in the Markdown Preview tab and in the option **Split Right**

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.107.1


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app/src/pane.js:916

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app/src/pane.js:916:21)
    at Pane.module.exports.Pane.split (/usr/share/atom/resources/app/src/pane.js:1017:21)
    at Pane.module.exports.Pane.splitRight (/usr/share/atom/resources/app/src/pane.js:972:25)
    at TabBarView.module.exports.TabBarView.splitTab (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:380:37)
    at Object.TabBarView.addElementCommands.tabs:split-right (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:137:32)
    at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:83:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:49.9.0 core:save (input.hidden-input)
     -4:25 intentions:highlight (input.hidden-input)
     -4:24.9.0 core:save (input.hidden-input)
  3x -4:08.4.0 core:backspace (input.hidden-input)
     -4:01.7.0 intentions:highlight (input.hidden-input)
     -4:01.6.0 github:commit (input.hidden-input)
     -3:54.6.0 core:confirm (input.input-text.github-CredentialDialog-Password)
     -1:44.2.0 intentions:highlight (input.hidden-input)
     -1:44.1.0 core:save (input.hidden-input)
     -1:35.9.0 intentions:highlight (input.hidden-input)
     -1:35.8.0 github:commit (input.hidden-input)
  2x -1:27.9.0 core:confirm (input.input-text.github-CredentialDialog-Password)
     -1:07.4.0 core:close (div.github-FilePatchView.is-staged)
  2x -0:57.4.0 pane:reopen-closed-item (div.markdown-preview.native-key-bindings)
     -0:37.8.0 tabs:split-left (div.title.icon.icon-markdown)
     -0:27.6.0 tabs:split-right (div.title.icon.icon-markdown)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-html-preview 0.2.2 
atom-minify 0.8.0 
atom-php-navigation 0.6.0 
atom-python-run 0.8.1 
atomic-chrome 0.3.2 
autocomplete-paths 2.11.0 
autocomplete-php 0.3.7 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
chmod 0.1.1 
codeigniter 0.3.2 
color-picker 2.2.5 
eval-javascript 1.2.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick-php 0.2.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-htmlhint 1.3.4 
linter-php 1.5.1 
linter-python 3.1.2 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.10 
markdown-writer 2.7.2 
merge-conflicts 1.4.5 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
php-introspector 1.0.0 
pigments 0.40.2 
python-debugger 0.2.0 
python-isort 0.0.7 
release-notes 0.53.0 
remote-sync 4.1.5 
split-diff 1.5.1 
sync-settings 0.8.3 
toggler 0.3.0 
```

**Comment by rsese** [comment]
Thanks for those steps @robertopc - I wasn't able to reproduce on Ubuntu 16.04 with Atom 1.21.  Can you update to 1.21 and let me know if you can still reproduce?  If you can, can you share a GIF or screencast of the behavior?
