### ISSUE TITLE
Failed to activate the tabs package in windows

### ISSUE THREAD

**Issue by BruceGujinhe** [atom/tabs#490]
Failed to activate the tabs package
atom.workspace.getElement is not a function
Hide Stack Trace
TypeError: atom.workspace.getElement is not a function
    at Object.activate (file:///C:/Users/Administrator/.atom/packages/tabs/lib/layout.coffee:4:20)
    at Object.activate (file:///C:/Users/Administrator/.atom/packages/tabs/lib/main.coffee:11:12)
    at Package.module.exports.Package.activateNow (C:\Atom\resources\app.asar\src\package.js:218:19)
    at C:\Atom\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Atom\resources\app.asar\src\package.js:96:15)
    at C:\Atom\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Atom\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Atom\resources\app.asar\src\package-manager.js:550:34)
    at C:\Atom\resources\app.asar\src\package-manager.js:352:19
    at C:\Atom\resources\app.asar\src\config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Atom\resources\app.asar\src\config.js:826:29)
    at Config.module.exports.Config.setRawValue (C:\Atom\resources\app.asar\src\config.js:612:19)
    at Config.module.exports.Config.set (C:\Atom\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\Atom\resources\app.asar\src\config.js:377:12)
    at Package.module.exports.Package.enable (C:\Atom\resources\app.asar\src\package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Atom\resources\app.asar\src\package-manager.js:173:14)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Atom\resources\app.asar\node_modules\settings-view\lib\package-card.js:353:25)

**Comment by 50Wliu** [comment]
It is highly unrecommended to manually install core packages.  To fix this issue, simply execute `apm uninstall tabs` from the command line and Atom will use the built-in tabs package instead.
