### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new...

### ISSUE THREAD

**Issue by mdalamsaikh** [atom/tabs#509]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.2

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:108

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:108:29)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:108:26)
    at GutterContainerComponent.update (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2920:18)
    at updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:108:26)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:369:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:266:16)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1423:18)
    at TextEditorComponent.didFocus (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1447:35)
    at HTMLElement.addEventListener (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:36:67)
    at HTMLElement.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:158:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:337:28)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:492:27)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
  5x -9:23.5.0 platformio-ide-terminal:copy (textarea.)
     -9:16.5.0 core:cut (textarea.)
  2x -9:15.9.0 platformio-ide-terminal:copy (textarea.)
     -5:28.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-bootstrap4 1.4.0 
atom-live-server 2.1.2 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.10 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.69.0 
linter 2.2.0 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-ui-default 1.6.4 
minimap 4.29.6 
minimap-pigments 0.2.2 
nuclide 0.243.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
terminal-plus 0.14.5 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
