### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by xorz57** [atom/tabs#521]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.107.1

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2272

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2261:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2254:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:401:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:285:18)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1468:18)
    at TextEditorComponent.didAttach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1435:20)
    at HTMLElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:41:25)
    at HTMLElement.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:138:24)
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:146:16)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:232:25)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:197:27)
    at /Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:240:30
    at wrapped (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app/src/pane.js:939:28)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:650:27)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:706:22)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

### Commands

```
     -0:54.1.0 core:move-right (input.hidden-input)
     -0:53.3.0 core:move-up (input.hidden-input)
     -0:52.5.0 core:select-down (input.hidden-input)
     -0:51.8.0 core:select-left (input.hidden-input)
  2x -0:43.2.0 core:move-up (input.hidden-input)
     -0:42.4.0 core:move-down (input.hidden-input)
  2x -0:41.9.0 core:select-down (input.hidden-input)
     -0:31.4.0 core:save (input.hidden-input)
  6x -0:30.7.0 core:move-up (input.hidden-input)
  8x -0:29.5.0 core:move-down (input.hidden-input)
  3x -0:27.8.0 core:move-up (input.hidden-input)
     -0:27 core:move-down (input.hidden-input)
  3x -0:26.8.0 core:select-down (input.hidden-input)
     -0:26 core:select-up (input.hidden-input)
  2x -0:22.3.0 core:backspace (input.hidden-input)
     -0:20.6.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment]
Thanks for opening an issue @xorz57.  I'm going to close this in favor of atom/atom#15668, as this is most likely an issue in Atom's new editor rendering code.

**Comment by xorz57** [comment]
No problem ;)
