### ISSUE TITLE
Uncaught TypeError: Cannot read property '-1' of undefined

### ISSUE THREAD

**Issue by schellappa** [atom/tabs#526]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.107.1

### Stack Trace

Uncaught TypeError: Cannot read property '-1' of undefined

```
At C:\Users\Swetha\AppData\Local\atom\app-1.20.1\resources\app\node_modules\text-buffer\lib\display-layer.js:542

TypeError: Cannot read property '-1' of undefined
    at DisplayLayer.getClipColumnDelta (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/text-buffer/lib/display-layer.js:542:45)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/text-buffer/lib/display-layer.js:351:36)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateToBufferMarkerLayerFindParams (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:253:59)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.findMarkers (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:141:27)
    at decorationCountsByLayer.forEach (~/AppData/Local/atom/app-1.20.1/resources/app/src/decoration-manager.js:92:41)
    at Map.forEach (native)
    at DecorationManager.decorationPropertiesByMarkerForScreenRowRange (~/AppData/Local/atom/app-1.20.1/resources/app/src/decoration-manager.js:91:40)
    at TextEditorComponent.queryDecorationsToRender (~/AppData/Local/atom/app-1.20.1/resources/app/src/text-editor-component.js:994:48)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.20.1/resources/app/src/text-editor-component.js:381:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.20.1/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.20.1/resources/app/src/text-editor-component.js:1468:18)
    at TextEditorComponent.didAttach (~/AppData/Local/atom/app-1.20.1/resources/app/src/text-editor-component.js:1435:20)
    at HTMLElement.attachedCallback (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-element.js:41:25)
    at HTMLElement.module.exports.PaneContainerElement.rootChanged (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.setRoot (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane-container.js:138:24)
    at PaneContainer.replaceChild (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane-container.js:146:16)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane-axis.js:232:25)
    at PaneAxis.module.exports.PaneAxis.removeChild (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane-axis.js:197:27)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/pane-axis.js:240:30
    at wrapped (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.destroy (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane.js:939:28)
    at Pane.module.exports.Pane.removeItem (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane.js:650:27)
    at Pane.module.exports.Pane.destroyItem (~/AppData/Local/atom/app-1.20.1/resources/app/src/pane.js:706:22)
    at TabBarView.module.exports.TabBarView.closeTab (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

### Commands

```
```

### Non-Core Packages

```
flatten-json 0.1.5 
formatter-json 1.0.1 
json-converter 0.2.4 
json-schema 0.1.15 
jsonlint 1.1.4 
markdown-pdf 2.1.0 
markdown-writer 2.7.2 
pretty-json 1.6.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
