### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by astrorCoder** [atom/tabs#556]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 3.1.4
**OS**: linux 5.0.0-arch1-1-ARCH
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.109.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /usr/lib/atom/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/usr/lib/atom/node_modules/text-buffer/lib/screen-line-builder.js:329:25)
    at ScreenLineBuilder.buildScreenLines (/usr/lib/atom/node_modules/text-buffer/lib/screen-line-builder.js:141:16)
    at DisplayLayer.getScreenLines (/usr/lib/atom/node_modules/text-buffer/lib/display-layer.js:638:35)
    at TextEditorComponent.queryScreenLinesToRender (/usr/lib/atom/src/text-editor-component.js:862:51)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/lib/atom/src/text-editor-component.js:376:10)
    at TextEditorComponent.updateSync (/usr/lib/atom/src/text-editor-component.js:266:10)
    at TextEditorComponent.flushPendingLogicalScrollPosition (/usr/lib/atom/src/text-editor-component.js:2031:12)
    at TextEditorComponent.didShow (/usr/lib/atom/src/text-editor-component.js:1463:12)
    at TextEditorComponent.didAttach (/usr/lib/atom/src/text-editor-component.js:1429:14)
    at HTMLElement.attachedCallback (/usr/lib/atom/src/text-editor-element.js:41:25)
    at HTMLElement.activeItemChanged (/usr/lib/atom/src/pane-element.js:152:22)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64:14)
    at Emitter.emit (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:257:28)
    at Pane.setActiveItem (/usr/lib/atom/src/pane.js:439:20)
    at Pane.activateItem (/usr/lib/atom/src/pane.js:579:12)
    at TabBarView.module.exports.TabBarView.onClick (/usr/lib/atom/node_modules/tabs/lib/tab-bar-view.js:727:19)
```

### Commands

```
```

### Non-Core Packages

```
indent-detective 0.3.2 
ink 0.9.14 
julia-client 0.7.13 
language-julia 0.18.0 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by rsese** [comment]
Thanks for the report!

> Atom: 1.34.0 x64
> Electron: 3.1.4

Based on these versions, it looks like you're using an unofficial build or distribution of Atom (the official stable 1.34.0 release ships with Electron 2.0.16).  Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
